[package]
name = "worldline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib"]

[dependencies]
anyhow = "1.0.86"
tracing = "0.1.40"

[build-dependencies]
duct = "0.13.7"
